name: Deploy Website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Deploy via SCP
      - name: Copy files to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          source: |
            ./*
            !.git/
            !.github/
          target: /var/www/michaelscybersite.net
