name: Deploy Website

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Debug - list repo files
        run: ls -R .

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /var/www/michaelscybersite.net/
          remote_host: ${{ secrets.DO_HOST }}
          remote_user: root
          remote_key: ${{ secrets.DO_SSH_KEY }}
