name: Deploy Website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Sync files to droplet
      uses: appleboy/rsync-action@v0.1.7
      with:
        host: ${{ secrets.DO_HOST }}
        username: root
        key: ${{ secrets.DO_SSH_KEY }}
        port: 22
        source: "./"
        target: "/var/www/michaelscybersite.net"
        delete: true
